### ISSUE TITLE
We should add some documentation in a "docs" folder

### ISSUE THREAD

**Issue by axd4** [it-at-m/digiwf-email-integration#2]
We should add some documentation in a "docs" folder:

- Quick Start (mainly the same as in the main readme)
- Architecture (we have a picture for this - be careful with relative paths)
- Element Templates (Operations)
- Everything else

Pls. use single files for every section.

_Originally posted by @xdoo in https://github.com/it-at-m/digiwf-email-integration/issues/1#issuecomment-1114519266_

**Comment by xdoo** [comment]
Could you pls. provide an image without red understrockes ;)

![image.png](https://images.zenhubusercontent.com/6220c3e56c0bae718921783b/c386b2d8-1760-4314-a9aa-3dd21815007a)

**Comment by xdoo** [comment]
Could you pls. document the Element Templates (Input / Output) Mapping?

**Comment by axd4** [comment]
@xdoo I incorporated your suggestions, please have another look.
I wasn't able to test the element template as the mail service is not yet deployed.

**Comment by axd4** [comment]
Also, see the pull request #4

**Comment by axd4** [comment]
Can we close this? @xdoo

**Comment by axd4** [comment]
Doc folder added
