### ISSUE TITLE
Load files from project specific S3 storage with presigned urls provided over payload

### ISSUE THREAD

**Issue by boal** [it-at-m/digiwf-email-integration#20]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to load files from the DigiWF S3 storage.

**Describe the solution you'd like**
It should be possible to transmit S3 presigned url via kafka. This S3 presigned url is then used to load the files from the S3 storage given by the url. No creation of presigned URLs within the integration component is necessary any more.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lmoesle** [comment]
Already implemented
