### ISSUE TITLE
Handle emails which could not be successfully sent

### ISSUE THREAD

**Issue by boal** [it-at-m/digiwf-email-integration#22]
If an email can not be delivered to the receiver (e.g. wrong email address, not existing email server on receiving side, ...) an error message should be returned to the digiwf process which is triggering the mail integration.

**Comment by boal** [comment]
Related epic:  https://github.com/it-at-m/digiwf-project/issues/107

**Comment by hloydl** [comment]
There might be a link to https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-project/299

**Comment by darenegade** [comment]
Dup #50
