### ISSUE TITLE
Replace list of attachmentPaths by list of attachments.

### ISSUE THREAD

**Issue by boal** [it-at-m/digiwf-email-integration#3]
**Is your feature request related to a problem? Please describe.**
It can be possible that an email attaches file from multiple s3-services. As a result, the url for each s3-service is needed.

**Describe the solution you'd like**

Replace in class `io.muenchendigital.digiwf.email.integration.domain.model.Mail` list of attachementPath of type string by list of attachments of type "Attachemt".

The Class attachment contains two attributes.

```java
public class Attachment {

    private String documentStorageUrl;

    private String pathToFile;

}
```

These two attributes can be used with the client lib.

```java
        final byte[] binaryFile = this.documentStorageFileRepository.getFile(
                attachment.getPathToFile(),
                attachment.getDocumentStorageUrl,
                3 // Expiration time
        );
```

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
n/a

**Comment by axd4** [comment]
Merged
