### ISSUE TITLE
Deploy mail artifact

### ISSUE THREAD

**Issue by axd4** [it-at-m/digiwf-email-integration#8]
Deploy the mail artifact to the digiwf infrastructure. We want to deploy it by building a docker image around the digiwf-mail-integration-starter library, pushing that to docker and incldue the docker image deployment to the digiwf gitops afterwards. All configuration will be exclusively handled in the docker runtime environment.

**Comment by xdoo** [comment]
@axd4  is this not a part of #62 ? I think this is not an Epic. You can see that by the length of the description ;P

**Comment by axd4** [comment]
@xdoo I thought it was said today in our daily that this is an epic. I concluded with boal afterwards and he also told me he'd make an epic for this with several subissues (create repo, create pipeline, create image?, ...) but we can have these sub issues as part of #62 too. I'll close this one then for now.

**Comment by xdoo** [comment]
@axd4 Sorry. Yes, we had discussed that. I just hadn't related this ticket to that because we had just talked about much more. You are welcome to open the Epic again, but then please add an appropriate description that is clear (even for forgetful people like me ;) what all needs to be done.
